backend/src/auth/keycloak-config.ts

Increase Timeout

---

frontend/src/views/SendRecords/SendRecords.tsx
frontend/src/views/SendRecords/components/submissionAgreement.tsx

Add Submission Agreement

---

backend/package-lock.json
backend/src/controller/upload-controller.ts
backend/src/middleware/uploadARIS66xMiddleware.ts
backend/src/models/digitalFile-model.ts
backend/src/models/interfaces/IDigitalFile.ts
backend/src/models/interfaces/ITransfer.ts
backend/src/repository/digitalList-repository.ts
backend/src/service/digitalFile-service.ts
backend/src/service/digitalFileList-service.ts
backend/src/service/transfer-service.ts
backend/src/utils/extractsDigitalFileList.ts
backend/src/utils/extractsFromAra66x.ts

Create Transfer, Digital File List and Digital File

Create Transfer, Digital File List and Digital File

---

backend/src/controller/upload-controller.ts
backend/src/repository/digitalFileList-repository.ts
backend/src/service/digitalFile-service.ts
backend/src/service/digitalFileList-service.ts
backend/src/service/transfer-service.ts

Refactory Transfer Service

---

backend/src/service/digitalFile-service.ts
backend/src/service/transfer-service.ts

Log Error Transfer

---

backend/src/controller/upload-controller.ts
backend/src/service/digitalFile-service.ts
backend/src/service/transfer-service.ts

Log Error Transfer and Create the Sub Folders

Log Error Transfer and Create the Sub Folders

---

backend/src/controller/digitalFile-controller.ts
backend/src/controller/digitalFileList-controller.ts
backend/src/controller/upload-controller.ts
backend/src/repository/digitalFileList-repository.ts
backend/src/repository/digitalList-repository.ts
backend/src/service/digitalFile-service.ts
backend/src/service/digitalFileList-service.ts
backend/src/service/transfer-service.ts

Save ARIS66xFile

---

backend/src/controller/upload-controller.ts

Update Response Message

---

backend/src/controller/upload-controller.ts
backend/src/service/transfer-service.ts

Optimize Upload Process

---

backend/src/controller/upload-controller.ts
backend/src/middleware/uploadARIS66xMiddleware.ts
backend/src/service/transfer-service.ts

Save ARIS617 PDF file

---

frontend/src/views/SendRecords/SendRecordsEDRMS.tsx
frontend/src/views/SendRecords/SendRecordsLAN.tsx
frontend/src/views/SendRecords/components/Aris617DropZone.tsx

Fix 617dropbox

---

frontend/src/views/SendRecords/SendRecordsLAN.tsx

fix 617Dropzone

---

backend/package.json
backend/src/controller/upload-controller.ts
backend/src/service/s3Client-service.ts
backend/src/service/transfer-service.ts

Upload ARIS617File To AWS

---

backend/src/service/s3Client-service.ts

Optimize the upload file code

---

backend/src/controller/transfer-controller.ts
backend/src/service/File-service.ts
backend/src/service/s3Client-service.ts

Upload PDF Agreement

---

backend/src/app.ts
backend/src/service/s3Client-service.ts

Upload ZipFile to S3

---

frontend/src/utils/xlsxUtils.tsx
frontend/src/views/CreateDigitalFileList/components/SelectFolder.tsx
frontend/src/views/SendRecords/SendRecordsEDRMS.tsx
frontend/src/views/SendRecords/SendRecordsLAN.tsx
frontend/src/views/SendRecords/components/Aris66xDropZone.tsx
frontend/src/views/SendRecords/components/DataportTxtDropZone.tsx
frontend/src/views/SendRecords/components/TransferComponent.tsx

added validations for upload file
added edit folder functionality if folder not exist
added delete functionality
added validations for create digital file list

added validations for upload file

---

backend/src/app.ts
backend/src/service/s3Client-service.ts

Optimize load processing

---

backend/src/app.ts
backend/src/service/s3Client-service.ts

Save Checksum

---

backend/src/service/s3Client-service.ts

Rename json file

---

backend/src/app.ts
backend/src/service/s3Client-service.ts

Rollback Status when an error was happened in the process of uploading files.

Rollback Status

---

backend/src/service/s3Client-service.ts

Add new folders in S3

---

.codeclimate.yml

This config defines configuration values for Code Climate's maintainability rating system.
This will help me evaluate the code's maintainability.

Added code climate config

---

.github/config/dep-report.json5
.github/config/vulnerability-report.json5
.github/helpers/github-api/create-and-close-existing-issue.mjs
.github/helpers/github-api/github-api-requests.mjs
.github/helpers/npm-audit/create-report-issues.cjs
.github/helpers/npm-audit/create-report.cjs
.github/helpers/npm-audit/enhance-vulnerability-list.cjs
.github/helpers/npm-audit/find-direct-dependencies.cjs
.github/helpers/npm-audit/find-indirect-vulnerable-deps.cjs
.github/helpers/npm-audit/get-latest-dep-info.cjs
.github/helpers/npm-audit/is-fix-available.cjs
.github/helpers/npm-audit/parse-npm-vulnerabilities.cjs
.github/helpers/npm-audit/run-npm-audit.cjs
.github/helpers/npm-deps/create-report-issues.cjs
.github/helpers/npm-deps/create-report.cjs
.github/helpers/npm-deps/parse-npm-deps.cjs
.github/helpers/parse-json5-config.cjs
.github/workflows/npm-audit-report.yaml
.github/workflows/npm-dep-report.yaml

Added two github workflows that create reports on out of date dependency versions and vulnerabilities.

Dependency management actions

---

desktop/shared/DATSCompanion.Shared/Models/MessageContract.cs
desktop/winservice/Behaviors/ReceiveMessageFromReactBehavior.cs
frontend/src/components/HealthCheck.tsx
frontend/src/components/layout/AppBar.tsx
frontend/src/types/constants.tsx
frontend/src/views/CreateDigitalFileList/components/SelectFolder.tsx
frontend/src/views/SendRecords/components/TransferComponent.tsx

added new react component to manage health checks and display a message to users

added new react component to manage healtch checks

---

backend/package.json
frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/components/Card/CardComponent.css
frontend/src/components/Card/CardComponent.tsx
frontend/src/components/layout/AppBar.tsx
frontend/src/views/CreateDigitalFileList/SplashScreen.tsx
frontend/src/views/Dashboard/Dashboard.tsx
frontend/src/views/LandingPage/Landing.css
frontend/src/views/LandingPage/Landing.tsx
frontend/src/views/SendRecords/SendRecords.tsx

- Updated landing page UI
- Updated dashboard UI
- Updated card styles
- Added splash screen to Create Digital File List
- Updated send records page UI

Brady UI UX changes

---

frontend/src/views/SendRecords/SendRecordsLAN.tsx
frontend/src/views/SendRecords/components/TransferComponent.tsx

- Requires all transfer documents to be uploaded before Next button can be pressed
- Disables upload button until previous upload has been made

Transfer UI

---

.github/workflows/helpers/update-wiki-table.py

[DAP-893](https://citz-cirmo.atlassian.net/browse/DAP-)

DAP-893: Update Wiki Table Script

---

.github/workflows/api-build-tag-push.yaml

[DAP-893](https://citz-cirmo.atlassian.net/browse/DAP-)

DAP-893:  Init Build Tag Push Github Action

---

README.md
desktop/src/main/index.ts
desktop/src/preload/api/checkAPIStatus.ts
desktop/src/preload/index.d.ts
desktop/src/preload/index.ts
desktop/src/renderer/src/App.tsx

[DAP-961](https://citz-cirmo.atlassian.net/browse/DAP-961)
- Added ability to change API URL - see README

DAP-961: API URL config

---

backend/src/modules/auth/middleware.ts
backend/tests/modules/auth/middleware.test.ts
desktop/cjs.workers.vite.config.ts
desktop/es.workers.vite.config.ts
desktop/package.json
desktop/src/preload/api/sso/fetchProtectedRoute.ts
desktop/src/preload/api/utils/safePromise.ts
desktop/src/preload/index.d.ts
desktop/src/renderer/src/App.tsx

- Refactored safePromise and fetchProtectedRoute to offer the entire response (however because of the way electron preload works the methods on the response object are striped when used in the renderer so I had to parse and apply `.json()` `.text()` and `.formData()` methods to `response.result`.
- Removed `p-limit` dep as its not used.
- Typo fix in backend response.

Desktop refactors

---

desktop/src/main/fileProcessing/WorkerPool.ts
desktop/src/main/fileProcessing/workers/copyWorker.ts

[DAP-968](https://citz-cirmo.atlassian.net/browse/DAP-968)

DAP-968: Worker error handling fix

---

README.md
desktop/package.json
desktop/src/main/index.ts
desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/assets/base.css
desktop/src/renderer/src/assets/main.css
desktop/src/renderer/src/components/SideNav.tsx
desktop/src/renderer/src/components/index.ts
desktop/src/renderer/src/main.tsx
desktop/src/renderer/src/pages/FileList.tsx
desktop/src/renderer/src/pages/Home.tsx
desktop/src/renderer/src/pages/SendRecords.tsx
desktop/src/renderer/src/pages/index.ts
desktop/src/renderer/src/theme.ts

- Added MUI and Design System
- Added side navigation and template pages
- Added BC-Sans

Added SideNav

---

desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/components/AuthButton.tsx
desktop/src/renderer/src/components/SideNav.tsx

[DAP-992](https://citz-cirmo.atlassian.net/browse/DAP-992)

DAP-992: Added login button to nav

---

desktop/src/main/fileProcessing/WorkerPool.ts
desktop/src/main/fileProcessing/processFolder.ts
desktop/src/main/fileProcessing/workers/copyWorker.ts
desktop/src/main/fileProcessing/workers/metadataWorker.ts
desktop/src/renderer/src/pages/Home.tsx

[DAP-988](https://citz-cirmo.atlassian.net/browse/DAP-988)
Now sends a message back to the processFolder function on the progress percentage.
Reminder to build the `out` directory again to see worker file changes reflected.

DAP-988: Added progress to workers

---

desktop/package.json
desktop/src/main/index.ts
desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/assets/main.css
desktop/src/renderer/src/components/file-list/FolderDisplayGrid.tsx
desktop/src/renderer/src/components/file-list/index.ts
desktop/src/renderer/src/pages/FileList.tsx

[DAP-977](https://citz-cirmo.atlassian.net/browse/DAP-977)
- Updated page layout for File List
- Updated page layout css
- Updated startup to open in maximized view
- Added Folder Data Grid/Table

DAP-977: Folder Data Grid/Table

---

desktop/src/main/fileProcessing/actions/copyFolderAndMetadata.ts
desktop/src/main/fileProcessing/actions/getFolderMetadata.ts
desktop/src/main/fileProcessing/actions/index.ts
desktop/src/main/fileProcessing/index.ts
desktop/src/main/fileProcessing/workers/copyWorker.ts
desktop/src/main/fileProcessing/workers/metadataWorker.ts
desktop/src/main/index.ts
desktop/src/preload/index.d.ts
desktop/src/preload/index.ts
desktop/src/renderer/src/components/ProcessFolderButton.tsx

[DAP-980](https://citz-cirmo.atlassian.net/browse/DAP-980)
- Separated processFolder function into a function for transfers and a function for file list
- Improved progress tracker for transfer function so it combined progress from both workers

DAP-980: processFolder modifications

---

.github/workflows/desktop-release.yaml
desktop/bump-version.js
desktop/package.json
desktop/src/main/index.ts

[DAP-938](https://citz-cirmo.atlassian.net/browse/DAP-938)
https://www.electron.build/auto-update.html

DAP-938: Desktop App Releases

---

desktop/package.json
desktop/src/main/index.ts
desktop/src/renderer/src/App.tsx

- Copies access token to clipboard for use in api calls

Copy token to clipboard

---

backend/src/modules/filelist/controllers/test.ts
backend/src/modules/filelist/entities/filelist.ts
backend/src/modules/filelist/schemas/create.ts
backend/src/modules/filelist/schemas/filelist.ts
backend/src/modules/filelist/schemas/index.ts
backend/src/modules/filelist/services/filelist.ts
backend/src/modules/filelist/utils/createJsonFileList.ts
backend/src/modules/filelist/utils/excel/addFileMetadata.ts
backend/src/modules/filelist/utils/excel/addFolderData.ts
backend/src/modules/filelist/utils/index.ts
backend/src/utils/formatDate.ts
backend/src/utils/index.ts
backend/tests/modules/filelist/controllers/create.test.ts
backend/tests/modules/filelist/controllers/test.test.ts
backend/tests/modules/filelist/entities/filelist.test.ts
backend/tests/modules/filelist/schemas/create.test.ts
backend/tests/modules/filelist/utils/createJsonFileList.test.ts

[DAP-984](https://citz-cirmo.atlassian.net/browse/DAP-984)
- Option to download file list as json file.
- Set type for outputFileType to enum of "excel" or "json"

DAP-984: JSON format file

---

desktop/src/main/fileProcessing/actions/index.ts
desktop/src/main/fileProcessing/actions/selectDirectory.ts
desktop/src/main/index.ts
desktop/src/preload/index.d.ts
desktop/src/preload/index.ts
desktop/src/renderer/src/assets/base.css
desktop/src/renderer/src/assets/main.css
desktop/src/renderer/src/components/file-list/ContinueButton.tsx
desktop/src/renderer/src/components/file-list/FolderDisplayGrid.tsx
desktop/src/renderer/src/components/file-list/SelectFolderButton.tsx
desktop/src/renderer/src/components/file-list/index.ts
desktop/src/renderer/src/pages/FileList.tsx

[DAP-978](https://citz-cirmo.atlassian.net/browse/DAP-978)
Adding buttons to Create File List page: 
- ContinueCutton currently does nothing
- SelectFolderButton:
- Takes in any current rows
- Allows user to select more directories
- This process is in main and opens a modal window
- Adds selected directories to current rows

Dap-978 Add Folder Button to Create File List Page

---

backend/README.md
backend/jest.config.js
backend/src/modules/filelist/controllers/create.ts
backend/src/modules/filelist/controllers/test.ts
backend/src/modules/filelist/entities/filelist.ts
backend/src/modules/filelist/services/filelist.ts
backend/src/modules/filelist/utils/createJsonFileList.ts
backend/src/modules/filelist/utils/email.ts
backend/src/modules/filelist/utils/index.ts
backend/src/modules/filelist/utils/queueConsumer.ts
backend/src/modules/rabbit/utils/queue/filelist.ts
backend/tests/modules/ches/controllers/email/test.test.ts
backend/tests/modules/filelist/controllers/test.test.ts
backend/tests/modules/filelist/utils/createJsonFileList.test.ts

[DAP-986](https://citz-cirmo.atlassian.net/browse/DAP-986)
See `backend/README` for testing instructions.
The consumer is the function that is called when the place in the queue has been reached.

DAP-986: File list consumer

---

.github/workflows/desktop-release.yaml

- This PR also attempts to fix the error that emerged regarding running clean install

Refactor TS error check to separate job.

---

.github/CODEOWNERS
.github/config/auto-assign-config.yaml
.github/workflows/desktop-release.yaml
.github/workflows/pr-auto-assign.yaml

- **This is a test.**
- **Updates PR auto assignment wf.**
- **Re-adds missing config.**
- **Adds pattern to CODEOWNERS.**

Fix PR Auto Assign & CODEOWNERS

---

desktop/src/renderer/src/assets/base.css
desktop/src/renderer/src/components/file-list/FolderDisplayGrid.tsx
desktop/src/renderer/src/pages/FileList.tsx

[DAP-996](https://citz-cirmo.atlassian.net/browse/DAP-996)
- Rows now save when you edit them
- Down key function to copy cell contents

DAP-996: Copy down & row edit saving

---

desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/components/SideNav.tsx
desktop/src/renderer/src/pages/Home.tsx
desktop/src/renderer/src/theme.ts

[DAP-995](https://citz-cirmo.atlassian.net/browse/DAP-995)
- Requires login to access tabs
- Home page to detail what to do

DAP-995: Require login + home page

---

desktop/src/renderer/src/pages/FileList.tsx

[DAP-1000](https://citz-cirmo.atlassian.net/browse/DAP-1000)

DAP-1000: Fix empty row bug

---

backend/src/modules/filelist/utils/email.ts
backend/src/modules/filelist/utils/queueConsumer.ts
desktop/src/renderer/src/pages/Home.tsx

[DAP-1006](https://citz-cirmo.atlassian.net/browse/DAP-1006)
- Updated email template
- Updated email subject and filename
- Updated wording on desktop Home page to match with email contact info.

DAP-1006: Updated email template

---

.github/workflows/desktop-release.yaml
desktop/package.json

- Changes desktop app build workflow matrix refs and names
- Alters script names in the desktop app package.json
to work with new workflow matrix

Implements OS specific deps. installs in desk wf.

---

.github/workflows/desktop-release.yaml

Electron Publish WF Changes

---

desktop/src/renderer/src/components/LeavePageModal.tsx
desktop/src/renderer/src/components/SideNav.tsx

[DAP-1011](https://citz-cirmo.atlassian.net/browse/DAP-1011)

DAP-1011: Added leave page confirmation

---

backend/src/modules/s3/controllers/health.ts
backend/src/modules/s3/utils/connection.ts
backend/src/modules/s3/utils/index.ts
backend/src/modules/s3/utils/upload.ts
backend/tests/modules/s3/controllers/health.test.ts

[DAP-1017](https://citz-cirmo.atlassian.net/browse/DAP-1017)
- Updated health check to return bucket info
- Added upload function

DAP-1017: Upload to s3

---

backend/src/modules/submission-agreement/controllers/get.ts
backend/src/modules/submission-agreement/controllers/index.ts
backend/src/modules/submission-agreement/router.ts
backend/tests/modules/submission-agreement/controllers/get.test.ts
backend/tests/modules/submission-agreement/router.test.ts

[DAP-991](https://citz-cirmo.atlassian.net/browse/DAP-991)
Waiting on `DAP-1033` to be merged.

DAP-991: GET Endpoint for Submission Agreement

---

backend/src/modules/filelist/controllers/create.ts
backend/src/modules/transfer/entities/transfer.ts
backend/src/modules/transfer/services/transfer.ts
backend/tests/modules/transfer/entities/transfer.test.ts

[DAP-1020](https://citz-cirmo.atlassian.net/browse/DAP-1020)
- Adds jobID and status to Transfer Model/Schema

DAP-1020: Transfer model additions

---

backend/package.json
backend/src/index.ts
backend/src/modules/transfer/services/transfer.ts

[DAP-1019](https://citz-cirmo.atlassian.net/browse/DAP-1019)
Adds method to get a sinle transfer given a where clause.
To test add the following to `backend\src\modules\health\controllers\services.ts` and call the endpoint.
```
const transfer = await TransferService.getTransferWhere({
"metadata.admin.accession": "1234567",
});
const data = {
s3: s3Connected,
rabbit: rabbitConnected,
ches: chesHealthy,
transfer,
};
```

DAP-1019: getTransferWhere method to Transfer service

---

backend/jest.config.js
backend/src/modules/transfer/utils/getFileFromZipBuffer.ts
backend/src/modules/transfer/utils/index.ts

[DAP-1055](https://citz-cirmo.atlassian.net/browse/DAP-1055)
No need to test. Copied function from test file in previous PR which was working.

DAP-1055: Added getFileFromZipBuffer

---

backend/jest.config.js
backend/src/modules/transfer/utils/email.ts
backend/src/modules/transfer/utils/index.ts

[DAP-1030](https://citz-cirmo.atlassian.net/browse/DAP-1030)

DAP-1030: Added email template

---

desktop/src/main/index.ts

Added dev api url

---

backend/docker/Dockerfile.prod
backend/package.json
backend/src/modules/transfer/utils/validateSubmissionAgreement.ts
backend/tests/modules/transfer/utils/validateSubmissionAgreement.test.ts
backend/tsconfig.json

Fix build issue

---

backend/src/index.ts
backend/src/modules/filelist/services/filelist.ts
backend/src/modules/filelist/utils/queueConsumer.ts
backend/src/modules/rabbit/utils/connection.ts
backend/src/modules/rabbit/utils/queue/filelist.ts
backend/src/modules/rabbit/utils/queue/test.ts
backend/src/modules/rabbit/utils/queue/transfer.ts
backend/src/modules/s3/utils/download.ts
backend/src/modules/s3/utils/upload.ts
backend/src/modules/transfer/controllers/create.ts
backend/src/modules/transfer/services/transfer.ts
backend/src/modules/transfer/utils/queueConsumer.ts
backend/src/utils/logs.ts

New log improvements

---

.github/CODEOWNERS

Add scott to codeowners

---

.github/CODEOWNERS

Sylar added to Codeowners

---

desktop/src/main/fileProcessing/actions/selectDirectory.ts
desktop/src/main/index.ts
desktop/src/preload/index.d.ts
desktop/src/preload/index.ts

[DAP-1088](https://citz-cirmo.atlassian.net/browse/DAP-1088)
Modifys selectDirectory function to allow specifying that we only want the user to select a single directory.
Will be used in a later PR `DAP-1080`. Can be tested by adding the new parameter to the selectDirectory function used in create file list.

DAP-1088: Single folder select

---

desktop/src/preload/api/transfer/index.ts
desktop/src/preload/api/transfer/isAccessionValid.ts
desktop/src/preload/api/transfer/isApplicationValid.ts
desktop/src/preload/api/transfer/parseXlsxFileList.ts
desktop/src/preload/index.d.ts
desktop/src/preload/index.ts
desktop/src/renderer/src/components/FileUploadArea.tsx
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1071](https://citz-cirmo.atlassian.net/browse/DAP-1071)
Added missing message for wrong file type in upload file component

DAP-1071: Wrong file type message

---

desktop/src/renderer/src/components/SideNav.tsx

Fixes an issue that wont become apparent until later PRs where navigating to another page from any other component outside of  the sidebar results in the sidebar display incorrectly displaying which tab you are on.
Nav should behave as normal.

Fix nav issue

---

backend/src/modules/submission-agreement/utils/createAgreementPDF.ts
desktop/src/renderer/index.html

API Troubleshooting

---

backend/src/modules/transfer/router.ts

[DAP-](https://citz-cirmo.atlassian.net/browse/DAP-)

its friday

---

backend/docker/Dockerfile.prod
backend/src/express.ts
backend/src/modules/submission-agreement/utils/createAgreementPDF.ts
desktop/src/global.d.ts

[DAP-1157](https://citz-cirmo.atlassian.net/browse/DAP-1157)
Limit increased to 50GB. We can adjust when we know how large the uploads will be.
Also trying to fix fonts.

DAP-1157: Increase req body size limit

---

backend/package.json
backend/src/modules/auth/controllers/token.ts

Updates token response to send refresh token so the user can stay logged in longer

Updated auth package and token response

---

desktop/src/renderer/src/pages/transfers/EdrmsTransfer.tsx

Tracks progress made for confirm leave page modal.

Track progress on edrms page

---

backend/src/modules/filelist/controllers/create.ts
backend/src/modules/filelist/entities/filelist.ts
backend/src/modules/filelist/schemas/create.ts
backend/src/modules/filelist/schemas/filelist.ts
backend/src/modules/filelist/services/filelist.ts
backend/src/modules/filelist/utils/createJsonFileList.ts
backend/src/modules/filelist/utils/queueConsumer.ts
backend/src/modules/transfer/controllers/edrms.ts
backend/src/modules/transfer/controllers/lan.ts
backend/src/modules/transfer/entities/transfer.ts
backend/src/modules/transfer/router.ts
backend/src/modules/transfer/schemas/transfer.ts
backend/src/modules/transfer/services/transfer.ts
backend/src/modules/transfer/utils/createStandardTransferZip.ts
backend/tests/modules/filelist/utils/createJsonFileList.test.ts

[DAP-1101](https://citz-cirmo.atlassian.net/browse/DAP-1101)
- Looks for extendedMetadata in request from filelist and lan transfer
- Adds original extendedMetadata from filelist to mongo
- Adds extendedMetadata to json output filelist
- Adds extended metadata to documentation folder of psps

DAP-1101: Get extended metadata

---

desktop/src/hooks/useFolderList/useFolderList.ts
desktop/src/renderer/src/pages/FileList.tsx

[DAP-1105](https://citz-cirmo.atlassian.net/browse/DAP-1105)
- Sends extendedMetadata to filelist endpoint when doing the `Create file list` in the app

DAP-1105: Send extended metadata in filelist

---

backend/src/modules/filelist/utils/excel/createExcelWorkbook.ts
backend/src/modules/filelist/utils/excel/updateFileListV2.ts
backend/tests/modules/filelist/utils/excel/createExcelWorkbook.test.ts

[DAP-1171](https://citz-cirmo.atlassian.net/browse/DAP-1171)
- Updates filelist tab names to use the current date instead of V1 and V2
Test by creating a file list in the app and seeing the tab names in the attached file list in the email

DAP-1171: Updated filelist tab names

---

backend/src/index.ts

[DAP-1153](https://citz-cirmo.atlassian.net/browse/DAP-1153)
Adds mongo usage stats to the server startup logs

DAP-1153: Added mongo usage stats log

---

desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/components/VPNPopup.tsx

[DAP-1128](https://citz-cirmo.atlassian.net/browse/DAP-1128)

DAP-1128: Implemented vpn popup designs

---

desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/components/SideNav.tsx
desktop/src/renderer/src/pages/FileListInstructions.tsx
desktop/src/renderer/src/pages/index.ts
desktop/src/renderer/src/pages/transfers/index.ts

[DAP-1131](https://citz-cirmo.atlassian.net/browse/DAP-1131)
Splitting up the `DAP-1131` ticket into more manageable branches.
Adds instructions page to create file list. https://www.figma.com/design/vGsZkC6g68J51myVbkEeeq/DATS-V2-Improvements?node-id=39-414&p=f&t=2Rn2DbeuYLesQBZo-0

DAP-1131: [Part 1] Filelist instructions page

---

desktop/src/renderer/src/assets/base.css
desktop/src/renderer/src/assets/main.css
desktop/src/renderer/src/components/file-list/AccAppCheck.tsx
desktop/src/renderer/src/components/file-list/AnimatedProgress.tsx
desktop/src/renderer/src/components/file-list/ContinueButton.tsx
desktop/src/renderer/src/components/file-list/FolderDisplayGrid.tsx
desktop/src/renderer/src/components/file-list/Instruction.tsx
desktop/src/renderer/src/components/file-list/SelectFolderButton.tsx
desktop/src/renderer/src/components/file-list/index.ts
desktop/src/renderer/src/pages/FileList.tsx

[DAP-1131](https://citz-cirmo.atlassian.net/browse/DAP-1131)
Implements designs for the create file list page https://www.figma.com/design/vGsZkC6g68J51myVbkEeeq/DATS-V2-Improvements?node-id=247-24442&t=2Rn2DbeuYLesQBZo-0
Doesnt include modals from designs

DAP-1131: [Part 2] Implement file list page designs

---

desktop/src/main/index.ts

- Added auto updater functions (yet to be tested)
- Added better app cleanup (task manager was showing app was still running after close).

App improvements

---

backend/src/modules/transfer/router.ts

[DAP-1165](https://citz-cirmo.atlassian.net/browse/DAP-1165)

DAP-1165: Increase multer limits

---

desktop/src/main/index.ts

Added prod urls

---

desktop/src/hooks/useFolderList/useFolderList.ts
desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/components/transfer/finish-view/FinishView.tsx
desktop/src/renderer/src/components/transfer/finish-view/RequestFailed.tsx
desktop/src/renderer/src/pages/FileList.tsx
desktop/src/renderer/src/pages/Home.tsx
desktop/src/renderer/src/pages/transfers/EdrmsTransfer.tsx
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1182](https://citz-cirmo.atlassian.net/browse/DAP-1182)
- Error handling on create file list, and send records
- Error screen on send records
- Fix home page buttons

DAP-1182: Error handling

---

.github/workflows/desktop-release.yaml

The application is looking for the latest.yml file but we arent adding it to the release assets

Fix desktop release action

---

desktop/src/renderer/src/components/HelpModal.tsx
desktop/src/renderer/src/components/SideNav.tsx
desktop/src/renderer/src/components/index.ts

[DAP-1190](https://citz-cirmo.atlassian.net/browse/DAP-1190)
https://www.figma.com/design/vGsZkC6g68J51myVbkEeeq/DATS-V2-Improvements?node-id=317-31868&t=QjFG5elrsmOGvVme-0

DAP-1190: Help modal

---

backend/src/modules/transfer/utils/queueConsumer.ts
backend/src/utils/logs.ts

[DAP-1066](https://citz-cirmo.atlassian.net/browse/DAP-1066)
Adds identifiable information to transfer logs such as jobID or accession and application numbers.

DAP-1066: Better api logs for transfer

---

desktop/src/renderer/src/pages/SendRecords.tsx

[DAP-1183](https://citz-cirmo.atlassian.net/browse/DAP-1183)

DAP-1183: Copywriting change on send records page

---

desktop/src/renderer/src/components/transfer/finish-view/FinishView.tsx
desktop/src/renderer/src/components/transfer/finish-view/RequestSuccess.tsx
desktop/src/renderer/src/pages/transfers/EdrmsTransfer.tsx
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1166](https://citz-cirmo.atlassian.net/browse/DAP-1166)

DAP-1166: Updated finish view copywriting

---

.github/workflows/desktop-release.yaml

Anotha one

---

desktop/src/renderer/src/pages/transfers/EdrmsTransfer.tsx
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1201](https://citz-cirmo.atlassian.net/browse/DAP-1201)
Checks the filename of transfer form and digital file list to match a regex pattern

DAP-1201: Check for filename

---

desktop/src/global.d.ts
desktop/src/main/index.ts
desktop/src/preload/api/workers/index.ts
desktop/src/renderer/src/App.tsx

[DAP-1202](https://citz-cirmo.atlassian.net/browse/DAP-1202)
Cancels worker when leaving the page so it stops collecting metadata and copying

DAP-1202: Cancel worker on page leave

---

desktop/src/renderer/src/components/view-transfers/ConfirmDeletionModal.tsx
desktop/src/renderer/src/components/view-transfers/index.ts

[DAP-1194](https://citz-cirmo.atlassian.net/browse/DAP-1194)

DAP-1194: Added confirm delete modal

---

desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1159](https://citz-cirmo.atlassian.net/browse/DAP-1159)

DAP-1159: Fixed duplicate toast messages

---

desktop/src/preload/api/transfer/parseXlsxFileList.ts
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx
desktop/src/renderer/src/pages/transfers/utils/getXlsxFileListToastData.ts

[DAP-1161](https://citz-cirmo.atlassian.net/browse/DAP-1161)

DAP-1161: Check for duplicate folders in file list

---

desktop/src/main/fileProcessing/workers/utilities/scripts/getExtendedMetadata.ps1

Adds more metadata fields to the extended metadata. The script will find:
- Standard File Properties (retrieved via Get-Item | Select-Object *)
- Extended File Properties (retrieved via the Windows Shell.Application COM Object using GetDetailsOf())

Added properties to extended metadata

---

desktop/src/global.d.ts
desktop/src/hooks/index.ts
desktop/src/hooks/useAppCloseHandler.ts
desktop/src/main/index.ts
desktop/src/preload/api/api.ts
desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/components/CloseApplicationModal.tsx
desktop/src/renderer/src/components/LeavePageModal.tsx
desktop/src/renderer/src/components/index.ts

[DAP-1136](https://citz-cirmo.atlassian.net/browse/DAP-1136)

DAP-1136: Close application warning

---

backend/src/index.ts
backend/src/modules/transfer/controllers/index.ts
backend/src/modules/transfer/controllers/view.ts
backend/src/modules/transfer/entities/transfer.ts
backend/src/modules/transfer/router.ts
backend/src/modules/transfer/services/transfer.ts
backend/src/modules/transfer/utils/queueConsumer.ts
backend/src/utils/logs.ts
backend/tests/modules/transfer/router.test.ts

[DAP-1126](https://citz-cirmo.atlassian.net/browse/DAP-1126)
Endpoint to get all completed transfers.
- Updated Postman

DAP-1126: Get transfers endpoint

---

backend/src/modules/filelist/utils/excel/updateFileListV2.ts

[DAP-1208](https://citz-cirmo.atlassian.net/browse/DAP-1208)

DAP-1208: Fix worksheet already exists

---

backend/src/modules/transfer/utils/createBagitFiles.ts
backend/src/modules/transfer/utils/createFinalTransfer.ts

[DAP-1152](https://citz-cirmo.atlassian.net/browse/DAP-1152)
Adds a new file to the transfer zip with checksums of the psp files

DAP-1152: Added psp manifest

---

backend/src/modules/transfer/controllers/lan.ts
backend/src/modules/transfer/services/transfer.ts

[DAP-1211](https://citz-cirmo.atlassian.net/browse/DAP-1211)

DAP-1211: Fix missing extended metadata

---

.env-template

Updated env template

---

desktop/src/main/fileProcessing/workers/utilities/scripts/getExtendedMetadata.ps1

Removed unused code, gather all extended metadata instead of just 300 entries, and use of "~" when empty value is found.

Extended metadata script updates

---

.github/workflows/desktop-release.yaml

Workflow wasnt adding release notes to commit

Fix desktop app release workflow

---

desktop/add-release-notes.js
desktop/package.json

Fix release notes script

---

desktop/add-release-notes.js
desktop/resources/release_notes.json

Script fix

---

.github/workflows/desktop-release.yaml
desktop/electron.vite.config.ts
desktop/es.workers.vite.config.ts
desktop/package.json
desktop/resources/release_notes.json

Another attempt to fix release notes. They weren't being added to the build files and the full release notes string wasnt being added to the json file.

Attempt to fix release notes

---

backend/src/modules/transfer/controllers/preserve.ts
desktop/resources/release_notes.json
desktop/src/renderer/index.html

[DAP-1221](https://citz-cirmo.atlassian.net/browse/DAP-1221)

DAP-1221: Fix libsafe upload

---

backend/jest.config.js
backend/src/modules/transfer/controllers/lan.ts
backend/src/modules/transfer/schemas/transfer.ts
backend/src/modules/transfer/utils/handleTransferChunkUpload.ts
backend/src/modules/transfer/utils/index.ts
backend/src/modules/uploads/TR_test_accession_test_app/chunk_0.bin
backend/src/modules/uploads/TR_test_accession_test_app/chunk_1.bin
backend/src/utils/logs.ts
backend/tests/utils/generateChecksum.test.ts

[DAP-1225](https://citz-cirmo.atlassian.net/browse/DAP-1225)
Want to test in OpenShift before completing EDRMS and standard transfers.

DAP-1225: API chunking (LAN Transfer)

---

desktop/src/renderer/src/components/transfer/finish-view/RequestLoading.tsx
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx
desktop/src/renderer/src/pages/transfers/utils/calculateChecksum.ts
desktop/src/renderer/src/pages/transfers/utils/index.ts

[DAP-1225](https://citz-cirmo.atlassian.net/browse/DAP-1225)

DAP-1225: Desktop app chunking for LAN transfer

---

desktop/src/main/index.ts

[DAP-1224](https://citz-cirmo.atlassian.net/browse/DAP-1224)

DAP-1224: Prevent save current version to release notes in dev

---

desktop/src/renderer/src/pages/transfers/EdrmsTransfer.tsx

[DAP-1225](https://citz-cirmo.atlassian.net/browse/DAP-1225)

DAP-1225: Transfer EDRMS chunking

---

backend/src/modules/transfer/controllers/create.ts
backend/src/modules/transfer/controllers/edrms.ts
backend/src/modules/transfer/controllers/lan.ts
backend/src/modules/transfer/schemas/transfer.ts
backend/src/modules/transfer/utils/callTransferEndpoint.ts
backend/src/modules/transfer/utils/handleTransferChunkUpload.ts
backend/src/utils/formatFileSize.ts
backend/src/utils/index.ts
backend/tests/modules/transfer/schemas/transfer.test.ts
backend/tests/utils/formatFileSize.test.ts

[DAP-1225](https://citz-cirmo.atlassian.net/browse/DAP-1225)

DAP-1225: Transfer zip chunking api

---

backend/src/modules/submission-agreement/controllers/decline.ts
backend/src/modules/submission-agreement/router.ts
backend/src/modules/submission-agreement/schemas/decline.ts
backend/src/modules/submission-agreement/schemas/index.ts
backend/src/modules/submission-agreement/utils/email.ts
backend/src/modules/submission-agreement/utils/index.ts

[DAP-1122](https://citz-cirmo.atlassian.net/browse/DAP-1122)

DAP-1122: Submission agreement decline endpoint

---

desktop/src/renderer/src/components/transfer/edrms-views/EdrmsSubmissionAgreementView.tsx
desktop/src/renderer/src/components/transfer/lan-views/LanSubmissionAgreementView.tsx
desktop/src/renderer/src/pages/transfers/EdrmsTransfer.tsx
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1122](https://citz-cirmo.atlassian.net/browse/DAP-1122)

DAP-1122: Submission agreement declines

---

backend/src/modules/transfer/schemas/transfer.ts

[DAP-1237](https://citz-cirmo.atlassian.net/browse/DAP-1237)
Fix for an error that occurs when you try uploading a transfer where you deleted folders and it returns an error saying that a property is missing from the folder changes metadata.

DAP-1237: Fix delete folder error

---

backend/src/modules/filelist/utils/excel/worksheets/folderListV2.ts

Fix type error

---

desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/assets/main.css
desktop/src/renderer/src/components/CloseApplicationModal.tsx

[DAP-1246](https://citz-cirmo.atlassian.net/browse/DAP-1246)

DAP-1246: Fix close application z index

---

desktop/package.json
desktop/src/renderer/src/components/Stepper.tsx
desktop/src/renderer/src/components/SubAgreementScrollBox.tsx
desktop/src/renderer/src/components/transfer/edrms-views/EdrmsConfirmationView.tsx
desktop/src/renderer/src/components/transfer/edrms-views/EdrmsSubmissionAgreementView.tsx
desktop/src/renderer/src/components/transfer/edrms-views/EdrmsUploadDataportView.tsx
desktop/src/renderer/src/components/transfer/edrms-views/EdrmsUploadFilelistView.tsx
desktop/src/renderer/src/components/transfer/edrms-views/EdrmsUploadFolderView.tsx
desktop/src/renderer/src/components/transfer/edrms-views/EdrmsUploadTransferFormView.tsx
desktop/src/renderer/src/components/transfer/finish-view/RequestFailed.tsx
desktop/src/renderer/src/components/transfer/finish-view/RequestLoading.tsx
desktop/src/renderer/src/components/transfer/finish-view/RequestSuccess.tsx
desktop/src/renderer/src/components/transfer/lan-views/LanConfirmationView.tsx
desktop/src/renderer/src/components/transfer/lan-views/LanSubmissionAgreementView.tsx
desktop/src/renderer/src/components/transfer/lan-views/LanUploadFileListView.tsx
desktop/src/renderer/src/components/transfer/lan-views/LanUploadTransferFormView.tsx
desktop/src/renderer/src/pages/transfers/EdrmsTransfer.tsx
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1242](https://citz-cirmo.atlassian.net/browse/DAP-1242)

DAP-1242: Stepper UI tweaks

---

desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1239](https://citz-cirmo.atlassian.net/browse/DAP-1239)

DAP-1239: Fix upload json filelist issue

---

.env-template
backend/docker/Dockerfile
backend/docker/Dockerfile.prod
compose.yaml
package.json

[DAP-1215](https://citz-cirmo.atlassian.net/browse/DAP-1215)

DAP-1215: Switch to podman

---

desktop/src/main/fileProcessing/actions/getFolderBuffer.ts
desktop/src/main/fileProcessing/actions/getFolderMetadata.ts
desktop/src/renderer/src/components/transfer/AccAppConfirmation.tsx
desktop/src/renderer/src/components/transfer/lan-views/LanConfirmationView.tsx
desktop/src/renderer/src/components/transfer/lan-views/LanSubmissionAgreementView.tsx
desktop/src/renderer/src/components/view-transfers/TransfersGrid/TransfersGrid.tsx
desktop/src/renderer/src/pages/transfers/LanTransfer.tsx

[DAP-1244](https://citz-cirmo.atlassian.net/browse/DAP-1244)
- UI change to remove "#" and "number" from "Accession" and "Application" within the app (exception of submission agreement).
- Fix issue uploading lan transfer where metadata wasnt being passed correctly to API.

DAP-1244: UI Change & Fix

---

desktop/src/renderer/src/assets/base.css
desktop/src/renderer/src/assets/main.css
desktop/src/renderer/src/components/FileUploadArea.tsx
desktop/src/renderer/src/components/HelpModal.tsx
desktop/src/renderer/src/components/Instruction/Instruction.tsx
desktop/src/renderer/src/components/PageLinkCard/PageLinkCard.tsx
desktop/src/renderer/src/components/SideNav/NavItem.tsx
desktop/src/renderer/src/components/SideNav/navItemData.tsx
desktop/src/renderer/src/components/file-list/AccAppCheck.tsx
desktop/src/renderer/src/components/file-list/ContinueButton.tsx
desktop/src/renderer/src/components/file-list/SelectFolderButton.tsx
desktop/src/renderer/src/components/transfer/AccAppConfirmation.tsx
desktop/src/renderer/src/pages/FileList.tsx
desktop/src/renderer/src/pages/home/HowDatsWorks.tsx
desktop/src/renderer/src/pages/home/instructionData.tsx
desktop/src/renderer/src/pages/transfers/EdrmsInstructions.tsx
desktop/src/renderer/src/pages/transfers/LanInstructions.tsx
desktop/src/renderer/src/pages/transfers/ViewTransfers.tsx
desktop/src/renderer/src/theme.ts

[DAP-1213](https://citz-cirmo.atlassian.net/browse/DAP-1213)

DAP-1213: Font updates

---

desktop/src/renderer/src/assets/main.css

[DAP-1261](https://citz-cirmo.atlassian.net/browse/DAP-1261)

DAP-1261: Checkbox styles

---

desktop/src/renderer/src/App.tsx
desktop/src/renderer/src/routes.tsx

[DAP-1268](https://citz-cirmo.atlassian.net/browse/DAP-1268)

change from browserrouter to hashrouter

---

desktop/src/renderer/src/components/SideNav/NavItem.tsx
desktop/src/renderer/src/components/SideNav/SideNav.tsx
desktop/src/renderer/src/components/SideNav/navItemData.tsx

[DAP-1259](https://citz-cirmo.atlassian.net/browse/DAP-1259)

DAP-1259: Sidenav ui changes

---

desktop/src/renderer/src/pages/transfers/ViewTransfers.tsx

[DAP-1267](https://citz-cirmo.atlassian.net/browse/DAP-1267)

DAP-1267: Text change on view status page

---

backend/src/modules/transfer/controllers/remove.ts
backend/src/modules/transfer/entities/transfer.ts
backend/src/modules/transfer/services/transfer.ts
backend/src/modules/transfer/utils/createBagitFiles.ts
backend/src/modules/transfer/utils/createPSP.ts
backend/src/modules/transfer/utils/getMetadata.ts
backend/src/modules/transfer/utils/queueConsumer.ts
backend/src/modules/transfer/utils/sortPSPContent.ts
backend/tests/modules/transfer/utils/createBagitFiles.test.ts
backend/tests/modules/transfer/utils/sortPSPContent.test.ts

[DAP-1271](https://citz-cirmo.atlassian.net/browse/DAP-1271)

DAP-1271: Soft delete transfers

---

backend/docker/Dockerfile
desktop/electron-builder.yml

[DAP-1303](https://citz-cirmo.atlassian.net/browse/DAP-1303)

DAP-1303: Potential fix for install issue

---

backend/src/modules/filelist/utils/excel/worksheets/metadata.ts

[DAP-1187](https://citz-cirmo.atlassian.net/browse/DAP-1187)
Removes unused file list fields

DAP-1187: Updated file list fields

---

backend/src/modules/transfer/utils/handleTransferChunkUpload.ts
backend/src/utils/streamToBuffer.ts

[DAP-1322](https://citz-cirmo.atlassian.net/browse/DAP-1322)

DAP-1322: Attempt to resolve buffer issue

---

backend/src/modules/transfer/utils/createStandardTransferZip.ts

[DAP-1322](https://citz-cirmo.atlassian.net/browse/DAP-1322)

DAP-1322: Attempt 2 to resolve memory spike in Openshift

---

backend/src/modules/transfer/utils/createStandardTransferZip.ts

[DAP-1322](https://citz-cirmo.atlassian.net/browse/DAP-1322)

DAP-1322: Debug logs

---

desktop/src/renderer/components/HelpModal.tsx

Fix type error, incorrect import

---

desktop/src/renderer/hooks/useFolderList/useFolderList.ts

[DAP-1359](https://citz-cirmo.atlassian.net/browse/DAP-1359)

change default opr to be true

---

desktop/src/preload/api/transfer/parseDataportJsonMetadata.ts

Fixes parsing of the dataport entries for Linda's file. The way we recognized that an entry was a folder and not a file was if it had an empty "Container" property but that is not the cause in Linda's file.

Fix EDRMS dataport parsing

---

desktop/electron.vite.config.ts

Attempt to fix electron build limit

---

backend/src/modules/transfer/controllers/create.ts
backend/src/modules/transfer/utils/queueConsumer.ts
backend/src/modules/transfer/utils/validateDigitalFileList.ts
backend/src/modules/transfer/utils/validateStandardTransferStructure.ts

[DAP-1379](https://citz-cirmo.atlassian.net/browse/DAP-1379)
Allows validated file names to be case insensitive in the backend.

DAP-1379: Case insensitive file names in backend

---

desktop/src/renderer/pages/transfers/EdrmsTransfer.tsx
desktop/src/renderer/pages/transfers/LanTransfer.tsx

[DAP-1379](https://citz-cirmo.atlassian.net/browse/DAP-1379)

change regex tests to be case insensitive

---

desktop/src/renderer/pages/transfers/EdrmsTransfer.tsx
desktop/src/renderer/pages/transfers/LanTransfer.tsx

[DAP-1387](https://citz-cirmo.atlassian.net/browse/DAP-1387)
A check is now in place during send records (when processing file list or data port file) to look for files ending in `.zip`.
If a zip file is found you will have to remove the zip file and try again.

DAP-1387: Check for zips in send records

---

.github/CODEOWNERS

Update CODEOWNERS to reflect github id change

---

backend/src/modules/filelist/controllers/create.ts
backend/src/modules/filelist/entities/filelist.ts
backend/src/modules/filelist/services/filelist.ts
backend/src/modules/transfer/utils/validateDigitalFileList.ts
desktop/src/preload/api/transfer/parseXlsxFileList.ts
desktop/src/renderer/components/transfer/AccAppConfirmation.tsx
desktop/src/renderer/components/transfer/edrms-views/EdrmsUploadDataportView.tsx
desktop/src/renderer/components/transfer/lan-views/LanUploadFileListView.tsx
desktop/src/renderer/pages/transfers/LanTransfer.tsx
desktop/src/renderer/pages/transfers/index.ts
desktop/src/renderer/pages/transfers/lanTransfer/LanTransfer.tsx
desktop/src/renderer/pages/transfers/lanTransfer/helpers.ts
desktop/src/renderer/pages/transfers/lanTransfer/types.d.ts

[DAP-1380](https://citz-cirmo.atlassian.net/browse/DAP-1380)

added text boxes for accession/application in lan transfer

---

desktop/src/renderer/components/transfer/finish-view/FinishView.tsx
desktop/src/renderer/components/transfer/finish-view/RequestLoading.tsx
desktop/src/renderer/pages/transfers/LanTransfer.tsx

[DAP-1378](https://citz-cirmo.atlassian.net/browse/DAP-1378)
Adds context to the LAN Send Records loading screen to let you know what stage of the request you're at such as "Sending part 1 of 3".

DAP-1378: LAN upload loading context
